### ISSUE TITLE
john-taylor-arms-venetian-filigree

### ISSUE THREAD

**Issue by jacopo81** [lovasoa/dezoomify#523] opened 2021-02-15 08:58 UTC
Hello
couldn't download the image with the standard tools:

https://www.artsy.net/artwork/john-taylor-arms-venetian-filigree

any advise?
Thanks!!

**Comment by lovasoa** [comment] 2021-02-15 09:18
Hello !
  This issue is a duplicate of https://github.com/lovasoa/dezoomify/issues/129

  You can [search existing issues here](https://github.com/lovasoa/dezoomify/issues) before opening a new one.

**Closed by lovasoa** 2021-02-15 09:18 UTC

**Comment by jacopo81** [comment] 2021-02-15 10:12
Sorry sorry sorry!

Il giorno lun 15 feb 2021 alle ore 10:19 Ophir LOJKINE <
notifications@github.com> ha scritto:

**Comment by lovasoa** [comment] 2021-02-15 10:32
Haha, no need to be sorry, you're welcome 😃

**Comment by jacopo81** [comment] 2021-02-15 10:46
😊

Il lun 15 feb 2021, 11:32 Ophir LOJKINE <notifications@github.com> ha
scritto:
