### ISSUE TITLE
artsandculture.google.com

### ISSUE THREAD

**Issue by nikos-nikou** [lovasoa/dezoomify#537] opened 2021-03-14 21:14 UTC
Hello everyone,

 I am having issues when trying to download https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA

Dezoomify reports:

```
Uncaught Error: Unable to fetch https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA
The server responded:
fopen(https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests


(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2021-03-15 07:48
duplicate of https://github.com/lovasoa/dezoomify/issues/337

**Closed** 2021-03-15 07:48 UTC

**Comment by lovasoa** [comment] 2021-03-15 08:53
See https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488
