### ISSUE TITLE
www.artsy.net

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#453] opened 2020-08-30 21:38 UTC
Hello!
Please explain how to download this enlarged image. I did not succeed using the methods known to me through dezoomify.
https://www.artsy.net/artwork/giusto-sustermans-portrait-of-ranuccio-ii-farnese-duke-of-parma-and-piacenza

**Comment by lovasoa** [comment] 2020-08-30 21:51
Duplicate of https://github.com/lovasoa/dezoomify/issues/129

**Closed by lovasoa** 2020-08-30 21:51 UTC
Labels: duplicate, new site support
