### ISSUE TITLE
beeldbank.spaarnestadphoto.com

### ISSUE THREAD

**Issue by zastas** [lovasoa/dezoomify#462] opened 2020-09-17 11:46 UTC
Hello everyone,

 I am having issues when trying to download https://beeldbank.spaarnestadphoto.com/_tiles/564f62637175454142677555544767714168716659413d3d.dzi

Dezoomify reports:

```
Uncaught Error: Unable to fetch https://beeldbank.spaarnestadphoto.com/_tiles/564f62637175454142677555544767714168716659413d3d.dzi

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:418)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2020-09-17 12:05
This URL does not seem to point to anything

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/552629/93468134-d2c12680-f8ee-11ea-9355-86bb29f38781.png">

**Comment by zastas** [comment] 2020-09-17 12:07
https://beeldbank.spaarnestadphoto.com/search.pp?showpicture=104554&page=1&pos=1#

Addition. I was able to open the image using the advice given here:
https://github.com/lovasoa/dezoomify/issues/457

**Comment by lovasoa** [comment] 2020-09-17 12:11
I think I understood your problem.
Te actual URL to use is the xml file you will find in the network monitor: 

[dezoomify https://beeldbank.spaarnestadphoto.com/_tiles/417a324b7871767677395043534f4a506976784635773d3d.xml](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://beeldbank.spaarnestadphoto.com/_tiles/417a324b7871767677395043534f4a506976784635773d3d.xml)

This is a bug in the dezoomify extension, which assumes the extension of deepzoom meta-information files is always a `.dzi`, whereas it sometimes ends in `.xml`.

**Comment by lovasoa** [comment] 2020-09-17 12:13
i am closing this issue as a duplicate of https://github.com/lovasoa/dezoomify-extension/issues/8

We will need to implement some kind of detection mechanism in the dezoomify extension to detect the `.xml` files.

**Closed** 2020-09-17 12:13 UTC
Labels: needinfo
