### ISSUE TITLE
https://artsandculture.google.com/ is no longer usable

### ISSUE THREAD

**Issue by mrchen0606** [lovasoa/dezoomify#396] opened 2020-05-15 14:52 UTC
https://artsandculture.google.com/asset/snow-lion/5gHFgoJvPTNNCw
![image](https://user-images.githubusercontent.com/65124511/82063952-bcb41700-96fe-11ea-822e-145d3161879b.png)

**Comment by lovasoa** [comment] 2020-05-15 20:44
This is a duplicate of https://github.com/lovasoa/dezoomify/issues/337

The easiest workaround is to use dezoomify-rs.

**Closed by lovasoa** 2020-05-15 20:44 UTC
Labels: bug, duplicate
