### ISSUE TITLE
artsandculture.google.com

### ISSUE THREAD

**Issue by PMKS72** [lovasoa/dezoomify#634] opened 2022-07-11 21:50 UTC
Hello everyone,

 I am having issues when trying to download https://artsandculture.google.com/asset/gela-sicily/7QHXcyMDmbhXOg

Dezoomify reports:

```
Error: Unable to find arts and culture image metadata URL

(https://dezoomify.ophir.dev/dezoomers/arts-culture.js:7)
```
I don't understand this message. Can someone please help me ?

**Comment by gerrith** [comment] 2022-07-13 08:22
#metoo
It started the last few days, suddenly more or less all downloads from Googlarts are failing. Some are working.
Examples:
Working:
https://artsandculture.google.com/asset/portrait-of-the-dancer-aleksandr-sakharov-jawlensky-alexej/ogGvLdZg_9FlIQ
NOT working:
https://artsandculture.google.com/asset/schlafende-sleeping-woman-alexej-von-jawlensky/jwHQL5q4ucGoWg

**Comment by lovasoa** [comment] 2022-07-22 12:42
Google had changed the format of their pages.
It's fixed in dezoomify now.

Duplicate of https://github.com/lovasoa/dezoomify/issues/638

**Closed by lovasoa** 2022-07-22 12:42 UTC
