### ISSUE TITLE
canmore.org.uk

### ISSUE THREAD

**Issue by Tartan2** [lovasoa/dezoomify#520] opened 2021-02-09 11:50 UTC
Trying to get the high res source images from canmore.org.uk

This site has a massive treasure trove of historical images. The site only offers low res for download.

Example: https://canmore.org.uk/collection/1830475

I get tile URL: https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0183/SC01830475.ptif/TileGroup0/4-5-0.jpg

Where the "4" is the zoom level (0-4) and I believe the "5" is the horizontal and the "0" is the vertical.

So I tried: https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0183/SC01830475.ptif/TileGroup0/4-{{X}}-{{Y}}.jpg - but it didn't work.

I have also never seen ".ptif" files before and if I save https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0183/SC01830475.ptif it's just a small image.

Sorry I am a bit of a noob and can't figure out dezoomify-rs. Can someone help?

**Comment by lovasoa** [comment] 2021-02-09 12:38
Duplicate of https://github.com/lovasoa/dezoomify/issues/481

**Closed by lovasoa** 2021-02-09 12:38 UTC
Labels: new site support

**Comment by lovasoa** [comment] 2021-02-09 12:40
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://zoom.rcahms.gov.uk/iipsrv?FIF=live/public/SC0183/SC01830475.ptif

**Comment by Tartan2** [comment] 2021-02-09 12:43
Thank you so much!
