### ISSUE TITLE
emuseum.mfah.org

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#405] opened 2020-06-16 16:34 UTC
Hello everyone,

 I am having issues when trying to download https://emuseum.mfah.org/internal/media/zoomdispatcher/315143/info.json

Dezoomify reports:

```
Error: Unable to fetch https://emuseum.mfah.org/internal/media/zoomdispatcher/315143/info.json

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:418)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2020-06-17 07:44
Duplicate of #406

**Closed by lovasoa** 2020-06-17 07:44 UTC
Labels: duplicate
