### ISSUE TITLE
Phillips - how to find the full sized image?

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#675] opened 2022-11-10 20:38 UTC
Can you check on this one from Phillips? I saw on an earlier page that it doesn't need dezoomify...

https://www.phillips.com/detail/pablo-picasso/NY010722/6

I can't seem to find anything but the small version (550px) of the painting.

**Comment by lovasoa** [comment] 2022-11-11 14:53
Duplicate of https://github.com/lovasoa/dezoomify/issues/578

The images are not tiled, this site doesn't need dezoomify

**Closed by lovasoa** 2022-11-11 14:53 UTC
Labels: new site support

**Comment by Tricesimo** [comment] 2022-11-11 23:11
I get that, but is there any way to find the full-sized image? I tried to find it the way that was done in #578, but I can't seem to find a similar file...

**Comment by lovasoa** [comment] 2022-11-12 00:21
you can use the network tab of your browser's devtools

![image](https://user-images.githubusercontent.com/552629/201446977-217eb3a8-045d-41be-b226-8059eb6df4ca.png)

https://assets.phillips.com/image/upload/t_Website_LotDetailZoomImage/v1666882395/auctions/NY010722/177458_001.jpg

**Comment by Tricesimo** [comment] 2022-11-12 05:50
Thanks!
