### ISSUE TITLE
[new site support] Microsculpture.net

### ISSUE THREAD

**Issue by Chaoticity** [lovasoa/dezoomify#517] opened 2021-01-23 17:57 UTC
### Site name and desciption
Microsculpture.net

A site dedicated to the Microsculpture exhibition put on by Levon Biss at Oxford University. Has zoomability for some of if not the largest and highest detail images of insects ever taken.

### Example URLs
http://microsculpture.net/tortoise-beetle.html
http://microsculpture.net/green-tiger-beetle.html

### Current error message
Dezoomify can't find an image at the above addresses, nor can the Firefox browser extension find any dezoomable images.

**Comment by lovasoa** [comment] 2021-01-23 19:58
Hello ! 
  We already have a thread for this site. You can search existing issues from the github issues list page before opening a new one.

Thanks.

Duplicate of https://github.com/lovasoa/dezoomify/issues/41

**Closed by lovasoa** 2021-01-23 19:58 UTC
Labels: new site support
