### ISSUE TITLE
[bug] black lines/spaces between tiles

### ISSUE THREAD

**Issue by AnotherCollector** [lovasoa/dezoomify#478] opened 2020-10-04 16:20 UTC
When using Firefox extension I noticed there are black lines/spaces between tiles, the problem isn't present in Dezoomify-rs. Any idea how to fix that?

**To Reproduce**
example:
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://gallica.bnf.fr/iiif/ark:/12148/btv1b52000446t/f25/info.json

**Browser:**
 - Firefox
 - 81.0.1 (64-bit)

Thank you

**Comment by lovasoa** [comment] 2020-10-04 19:58
Hello !
  This is a known bug, it's already being tracked in https://github.com/lovasoa/dezoomify/issues/364

**Comment by lovasoa** [comment] 2020-10-04 19:59
Duplicate of #364

**Closed by lovasoa** 2020-10-04 19:59 UTC
Labels: bug
