### ISSUE TITLE
DZI-problem at badigit.comune.bologna.it/mappe/Tsfoglia01.asp

### ISSUE THREAD

**Issue by mapper2** [lovasoa/dezoomify#480] opened 2020-10-18 10:35 UTC
I am not sure if this is a new site issue or just a DZI issue, but maps at http://badigit.comune.bologna.it/mappe/Tsfoglia01.asp?start=37 are not downloadable 

http://badigit.comune.bologna.it/mappe/303/GeneratedImages/dzc_output_files/11/2_2.jpg
"An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave."

I've tried looking at the newtwork traffic but no luck

Great collection of historical maps of the Bologna region of Italy

Best

**Comment by lovasoa** [comment] 2020-10-18 10:46
Duplicate of https://github.com/lovasoa/dezoomify-extension/issues/8

**Closed by lovasoa** 2020-10-18 10:46 UTC
Labels: new site support

**Comment by lovasoa** [comment] 2020-10-18 10:48
dezoomify-extension assumes the extension is `.dzi` whereas it is in fact `.xml`.

In your case : `http://badigit.comune.bologna.it/mappe/303/GeneratedImages/dzc_output.xml`

**Comment by lovasoa** [comment] 2020-10-18 11:06
I updated dezoomify so you should now be able to give it directly the tile url http://badigit.comune.bologna.it/mappe/303/GeneratedImages/dzc_output_files/11/2_2.jpg

**Comment by mapper2** [comment] 2020-10-18 14:52
Great, thank you. Much appreciated.

One odd thing though. Chrome won't download it, but Edge works flawlessly (and I have only two add-ons: dezoomify and ad-blocker--dezoomify is whitelisted just in case). The #8 valencienne link works also altough the Chrome add-on did not manage to find the URL.

Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://badigit.comune.bologna.it/mappe/219/GeneratedImages/dzc_output.xml
(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:208)
