### ISSUE TITLE
New site support: https://www.artsy.net/

### ISSUE THREAD

**Issue by jhoward1045** [lovasoa/dezoomify#590] opened 2021-12-08 16:11 UTC
https://www.artsy.net/artwork/anselmo-ballester-incantesimo-nei-mari-del-sud-the-blue-lagoon

**Comment by lovasoa** [comment] 2021-12-08 18:13
duplicate of https://github.com/lovasoa/dezoomify/issues/129

**Closed** 2021-12-08 18:13 UTC
