### ISSUE TITLE
Uncaught Error: Unable to find google arts image token  (https://ok.daoing.com/he/dezoomers/google-arts-culture.js?v=2.2:14) You should read our Frequently Asked Questions, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker.

### ISSUE THREAD

**Issue by scxdt111** [lovasoa/dezoomify#332] opened 2019-10-18 01:07 UTC
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Include an URL to a zoomable image viewer page AND the URL you are giving to dezoomify.

**Expected behavior**

**Screenshots**

**Browser:**

**Additional context**

**Comment by lovasoa** [comment] 2019-10-18 06:03
Can you please fill in the bug? It looks like you left the default template...

**Comment by lovasoa** [comment] 2019-10-18 07:51
I am closing this until the details are properly filled. I'll reopen it as soon as this has enough info to actionable.

**Closed by lovasoa** 2019-10-18 07:51 UTC
Labels: bug

**Comment by lovasoa** [comment] 2019-10-22 20:58
The URL you mention (https://ok.daoing.com/he) is **not the official dezoomify mirror** ! It was probably not upgraded with the latest commits made to dezoomify.

If you want to always use the latest version of dezoomify, please use the [**official dezoomify site on ophir.alwaysdata.net/dezoomify**](https://ophir.alwaysdata.net/dezoomify)

Please report as github issues only issues that you can reproduce with the latest version of dezoomify (that runs on https://ophir.alwaysdata.net/dezoomify)

**Comment by lovasoa** [comment] 2019-10-22 21:00
On a related note: if someone is interested in maintaining a chinese translation of dezoomify, please open an issue here and I'll be happy to discuss it, and host it on the official mirror.
