### ISSUE TITLE
[bug] Dezoomify was unable to load tiles from IIIF, extension found the JSON file needed

### ISSUE THREAD

**Issue by CodemasterTH** [lovasoa/dezoomify#550] opened 2021-05-12 19:06 UTC
Hello, i tried to download the zoomable image from http://www.fotografia.iccd.beniculturali.it/iiif/mirador.html?manifest=https://dati.beniculturali.it/media/manifest/1/P000229. 
I used dezoomify extension and it found the IIIF metainformation file at http://2.42.229.81/iiif/2/1%2F449.TIF/info.json
When i click on dezoomify button, it gives the error:
`Uncaught Error: Unable to load first tile: http://2.42.229.81/iiif/2/1%2F449.TIF/0,0,884,884/884,/0/default.jpg`
Chrome version 90.0.4430.212
![image](https://user-images.githubusercontent.com/26440866/118030485-bec5ab80-b33b-11eb-90f5-a1ffc34f527d.png)
I didn't add this report as "new site support" because the site uses IIIF and the needed metainformation file was found.

**Comment by lovasoa** [comment] 2021-05-12 19:42
Duplicate of https://github.com/lovasoa/dezoomify/issues/542

See the FAQ.

**Closed by lovasoa** 2021-05-12 19:42 UTC
Labels: duplicate

**Comment by lovasoa** [comment] 2021-05-12 19:47
![canvas](https://user-images.githubusercontent.com/552629/118035514-93f34b80-b36b-11eb-823b-1aaa1fae07a2.jpg)

**Comment by CodemasterTH** [comment] 2021-05-12 19:57
Thanks for the answer, the solution for the other issue worked well.
But regarding to the FAQ.
The error i posted here is not listed in the FAQ. It is the same solution for the "internet correction" error indeed, but "Uncaught Error: Unable to load first tile" is not the one listed. 
Therefore i suggest you to update the FAQ to add it.
