### ISSUE TITLE
Oops, we have a problem An error occured while trying to dezoomify your image. https://artsandculture.google.com/

### ISSUE THREAD

**Issue by Leonidas120** [lovasoa/dezoomify#390] opened 2020-05-05 21:24 UTC
### https://artsandculture.google.com/

https://artsandculture.google.com/asset/portret-fryderyka-chopina-nicolas-eustache-maurin/xQFSAU3_VZEVIw

Oops, we have a problem
An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.

You can try to install the dezoomify browser extension, that can find the address of dezoomable images automatically on the pages you visit.

If that does not help, then you should read our Frequently Asked Questions.

If your image is extremely large and it does not show in your browser, see our advices for large images.

.....................................................

**Comment by lovasoa** [comment] 2020-05-05 21:53
Hello, 
  What is the exact technical error message, displayed at the bottom of the page ? Did you check the existing issues to check whether this had already been reported ? (Are you sure this is not a duplicate of #386 ?)

**Comment by Leonidas120** [comment] 2020-05-05 22:54
It doesn't work, no way

**Comment by lovasoa** [comment] 2020-05-05 23:39
Can you please answer these questions:

 - What is the exact technical error message, displayed at the bottom of the page ? 

 - Did you check the existing issues to see whether your problem had already been reported ? 

 - Are you sure this is not a duplicate of the following issue : #337 ?

**Comment by lovasoa** [comment] 2020-05-10 20:42
OK, I'll close the issue for the moment. If you have more information to provide, give them below and we'll reopen this thread if necessary.

**Closed by lovasoa** 2020-05-10 20:42 UTC
Labels: needinfo
