### ISSUE TITLE
Error downloading Google Arts Pictures

### ISSUE THREAD

**Issue by privatespacekees** [lovasoa/dezoomify#531] opened 2021-02-26 20:06 UTC
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**
Uncaught Error: Unable to fetch https://artsandculture.google.com/asset/a-clearing-in-the-forest-john-russell/tQHdrMa23Ukx5g
The server responded:
fopen(https://artsandculture.google.com/asset/a-clearing-in-the-forest-john-russell/tQHdrMa23Ukx5g): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)

**Comment by lovasoa** [comment] 2021-02-26 22:16
Duplicate of #337

See https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488

**Closed** 2021-02-26 22:16 UTC
Labels: bug
