### ISSUE TITLE
Is not working with Artsy lately, is it?

### ISSUE THREAD

**Issue by funkarlos** [lovasoa/dezoomify#195] opened 2017-12-28 12:12 UTC
https://www.artsy.net/artwork/lucien-clergue-jeux-de-lete-paris

Like that image for instance. I've been getting the error more often than before, and by often I mean every time ^^"

Any idea?

Thanks for the tool anyway!

**Comment by lovasoa** [comment] 2020-08-30 21:52
Duplicate of #129

**Closed by lovasoa** 2020-08-30 21:52 UTC
