### ISSUE TITLE
www.artsy.net

### ISSUE THREAD

**Issue by Texas3000** [lovasoa/dezoomify#535] opened 2021-03-08 11:05 UTC
Hello everyone,

I am having issues when trying to download Deepzoom pictures on https://www.artsy.net/

Is it possible to add support for it ?

Dezoomify reports:

```
Error: Unable to fetch https://d1s2w0upia4e9w.cloudfront.net/assets-novo/Microsoft.XML

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)

```
Error: Unable to find a proper dezoomer for:
https://www.artsy.net/artwork/rembrandt-van-rijn-ephraim-bonus-jewish-physician-1647

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2021-03-08 12:18
duplicate of https://github.com/lovasoa/dezoomify/issues/129

**Closed by lovasoa** 2021-03-08 12:18 UTC
