### ISSUE TITLE
How to download this zoomable map

### ISSUE THREAD

**Issue by sajaypal007** [lovasoa/dezoomify#431] opened 2020-08-04 18:18 UTC
[How to download this map](http://digitool.is.cuni.cz/R/LIQNN3C97FKLI4YPUDH671G5GS6AQI768R4SICQ7R18H62TC4E-00059?func=dbin-jump-full&object_id=1172022&silo_library=GEN01&pds_handle=GUEST) 

When clicked the image, it opens in a zoomable viewer.

**Comment by lovasoa** [comment] 2020-08-07 15:55
Hi !
  This is a duplicate of #412. Feel free to comment in that issue.

**Closed by lovasoa** 2020-08-07 15:55 UTC

**Comment by lovasoa** [comment] 2020-08-07 16:13
![imageserver](https://user-images.githubusercontent.com/552629/89665867-a373ce80-d8d9-11ea-8f51-294ba7441b71.jpeg)

**Comment by sajaypal007** [comment] 2020-08-07 22:53
Thanks a lot
