### ISSUE TITLE
Unable to dezoomify from ČÚZK Portal

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify#297] opened 2019-05-30 13:15 UTC
I can't download zoomable cadastral maps by clicking "_Stabilní katastr spojený_" from the **ČÚZK Portal** (url: https://archivnimapy.cuzk.cz/uazk/pohledy/archiv.html). An example from the Municipality of _Slezské Pavlovice_: https://archivnimapy.cuzk.cz/uazk/com/com_data/2784-2/2784-2-003_index.html.
Unfortunately, there's another issue about this problem (https://github.com/lovasoa/dezoomify/issues/142), but **no one has ever responded** and I believe that [psinacio](https://github.com/psinacio) has desisted or, more likely, went somewhere else.
Please, does anyone know a solution?
Regards.

**Comment by lovasoa** [comment] 2019-05-30 15:58
I am closing this as a duplicate of #142. There are many requests for new site support, and I'd rather avoid duplicates. If anyone is interested in contributing to add support for this site, there is [a guide](https://github.com/lovasoa/dezoomify/wiki/How-to-add-support-for-a-new-website) on our wiki on how to do so.

**Closed by lovasoa** 2019-05-30 15:58 UTC
Labels: duplicate, new site support
