### ISSUE TITLE
artsandculture.google.com

### ISSUE THREAD

**Issue by gerrith** [lovasoa/dezoomify#636] opened 2022-07-13 08:36 UTC
Hello everyone,

 I am having issues when trying to download https://artsandculture.google.com/asset/schlafende-sleeping-woman-alexej-von-jawlensky/jwHQL5q4ucGoWg

Dezoomify reports:

```
Uncaught Error: Unable to find arts and culture image metadata URL

(https://dezoomify.ophir.dev/dezoomers/arts-culture.js:7)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2022-07-22 12:39
Duplicate of https://github.com/lovasoa/dezoomify/issues/638

It's fixed now.

 https://dezoomify.ophir.dev/#https://artsandculture.google.com/asset/schlafende-sleeping-woman-alexej-von-jawlensky/jwHQL5q4ucGoWg

**Comment by lovasoa** [comment] 2022-07-22 12:40
![dezoomify-result](https://user-images.githubusercontent.com/552629/180441075-7903bfe7-1948-44a0-8035-aa14e83530f0.jpg)

**Closed by lovasoa** 2022-07-22 12:39 UTC
