### ISSUE TITLE
New site support: fineartamerica.com

### ISSUE THREAD

**Issue by jhoward1045** [lovasoa/dezoomify#494] opened 2020-11-29 22:38 UTC
https://fineartamerica.com/featured/automobile-club-vintage-automobile-ads-and-posters.html
I'd really appreciate any help on getting this image at its full size.

**Comment by lovasoa** [comment] 2020-11-30 07:34
duplicate of https://github.com/lovasoa/dezoomify/issues/267

**Closed** 2020-11-30 07:34 UTC
