### ISSUE TITLE
（Google Arts and Culture）can not work

### ISSUE THREAD

**Issue by ztjion520** [lovasoa/dezoomify#434] opened 2020-08-10 19:09 UTC
Hi
It can be used normally at the end of July, but it cannot be used today.
Hope you can fix it,I love this project so much！
Thank you.
![BUG](https://user-images.githubusercontent.com/69480628/89820525-bb6c7c00-db7f-11ea-8cdd-d5fefc591f59.jpg)

Test site:
https://artsandculture.google.com/asset/ggF7tlS8IEcAGA

Problem Description:

Uncaught Error: Unable to fetch https://artsandculture.google.com/asset/ggF7tlS8IEcAGA
The server responded:
fopen(https://artsandculture.google.com/asset/ggF7tlS8IEcAGA): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:418)

**Comment by ztjion520** [comment] 2020-08-10 19:25
Supplement:
Browser：chrome（Version 78.0.3904.87 (official version) (64-bit)）

I also tried using：dezoomify-rs，Still unable to download
![QQ截图20200811032317](https://user-images.githubusercontent.com/69480628/89822161-549c9200-db82-11ea-8d20-ab8e69dadc41.jpg)

**Comment by lovasoa** [comment] 2020-08-10 20:05
Duplicate of #337

**Closed by lovasoa** 2020-08-10 20:05 UTC
Labels: bug

**Comment by lovasoa** [comment] 2020-08-10 20:10
You can open a separate issue on dezoomify-rs if you want, but I can't reproduce the issue. dezoomify-rs downloads the image just fine on my computer.

By the way, if you want to download this picture, it is available on wikimedia commons: https://commons.wikimedia.org/wiki/File:La_Fresnaye,_Roger_de_-_The_Canal,_Brittany_Landscape_-_Google_Art_Project.jpg
