### ISSUE TITLE
stuck on "Preparing tiles load..." on a supported site

### ISSUE THREAD

**Issue by zastas** [lovasoa/dezoomify#547] opened 2021-05-07 16:18 UTC
### Site name and desciption
National Library of Ireland's online catalogue
http://catalogue.nli.ie/

Provides access to most of the print collections, including the handwritten and visual collections cataloged since 1990, as well as records from some of the earlier catalogs. Also available are thousands of items from the collections that have been digitized. This includes over 33,000 glass plate negatives.

### Example URLs
- http://catalogue.nli.ie/Record/vtls000334760
- http://catalogue.nli.ie/Record/vtls000335574

- http://catalogue.nli.ie/cgi-bin/iipsrv.fcgi?FIF=000340000/000334760/vtls000334760_001.jp2&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number
- http://catalogue.nli.ie/cgi-bin/iipsrv.fcgi?FIF=000340000/000335574/vtls000335574_001.jp2&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number

### Current error message
A window opens with a preparation for loading and a message "Preparing tiles load... (0%)". But then the download does not start. 
![Image 578](https://user-images.githubusercontent.com/68678470/117479264-c87c9700-af68-11eb-9b2f-b33d512f773b.png)

**Comment by lovasoa** [comment] 2021-05-07 16:39
It works fine for me

![canvas](https://user-images.githubusercontent.com/552629/117481595-7d13ba00-af63-11eb-94bb-efd81961dd39.jpg)

**Comment by lovasoa** [comment] 2021-05-07 16:41
Can you disable all your browser extensions and try again, to see if one of them is causing the issue ?
Do you have this problem in all browsers ?
Can you take a screenshot of your browser's developer tools (console and network panel) panel when dezoomify seems to be stuck ?

**Comment by lovasoa** [comment] 2021-05-07 17:50
I see, this is an instance of that bug : https://github.com/lovasoa/dezoomify/issues/542

See the discussion in that thread for a workaround.
I will close this issue as a duplicate.

**Comment by lovasoa** [comment] 2021-05-07 17:50
Duplicate of #542

**Closed by lovasoa** 2021-05-07 17:50 UTC
Labels: needinfo

**Comment by lovasoa** [comment] 2021-05-07 17:53
Link to the FAQ: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#i-see-an-error-saying-check-that-your-internet-connection-is-working-and-that-you-can-access-this-url-http

**Comment by lovasoa** [comment] 2021-05-07 22:05
If you can, I encourage you to contact the National Library of Ireland and report that you are seeing an error when loading their library in HTTPS, and that fixing this issue would give better security and privacy to all their users.
