### ISSUE TITLE
Sothebys Images

### ISSUE THREAD

**Issue by chengischan** [lovasoa/dezoomify#566] opened 2021-07-31 15:01 UTC
Can anyone help do the same thing for Sothebys images to download them in high res, like the issue was solved below for a Bonhams image. 

Example of an image url on Sothebys

https://sothebys-md.brightspotcdn.com/dims4/default/4313cb0/2147483647/strip/true/crop/1247x2000+0+0/resize/800x1283!/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fmedia-desk%2F7f%2F64%2F59d75c844269a9953b0bd64f1f21%2F085n10645-bmph2-01.jpg

which part of the source code do I replace to extract the unmodified high res image? 
Thank you

```
http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&tile=1:1
```

If you can want to download other images from the same site, open the source code of the page in which the image is in your browser.

Search for a part that looks like

```html
<img
			src="http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&amp;width=640&amp;height=480&amp;autosizefit=1"
			alt="Adolphe Alexandre Lesrel (French, 1839-1929) A winning hand"
			title="Adolphe Alexandre Lesrel (French, 1839-1929) A winning hand"
			class="autogallery clickable"
			
		/>
```

Extract the image source url. In this case, this is `http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&amp;width=640&amp;height=480&amp;autosizefit=1`

Replace the end of the url (everything after `.jpg`) by `&tile=1:1`. In this case, you get `http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&tile=1:1`

_Originally posted by @lovasoa in https://github.com/lovasoa/dezoomify/issues/123#issuecomment-280367957_

**Comment by lovasoa** [comment] 2021-08-02 08:58
Duplicate of https://github.com/lovasoa/dezoomify/issues/509

You can comment there if needed.

**Closed by lovasoa** 2021-08-02 08:58 UTC
