### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by Elementalel** [lovasoa/dezoomify#568] opened 2021-08-01 02:30 UTC
How can I use dezoomify for this link for example? You need to log in in order to get access to it though, but 
I don't know where to put the {{x}} and {{y}} and whether it will work if I download the browser addon:

https://search.arch.be/imageserver/getpic.php?513/513_9999_999/513_9999_999_1144630_000/513_9999_999_1144630_000_0_0008.jp2&121

thanks

**Comment by lovasoa** [comment] 2021-08-02 08:48
Duplicate of https://github.com/lovasoa/dezoomify/issues/53

Please comment there if needed.

**Closed by lovasoa** 2021-08-02 08:48 UTC
Labels: new site support
