### ISSUE TITLE
Problem with britishmuseum.org

### ISSUE THREAD

**Issue by UtopianElectronics** [lovasoa/dezoomify#770] opened 2023-12-29 16:08 UTC
I'm trying to download this [image](https://www.britishmuseum.org/collection/object/P_2018-7009-11-1), and while dezoomify detects [this](https://media.britishmuseum.org/iiif/Repository/Documents/2018_2/21_14/8a50c80c_405a_4136_ab8b_a88e00ea42e3/PPA24814.ptif/info.json) as the source, the webpage it opens fails to grab the tiles and make the image:
```
Error: Invalid JSON:
https://media.britishmuseum.org/iiif/Repository/Documents/2018_2/21_14/8a50c80c_405a_4136_ab8b_a88e00ea42e3/PPA24814.ptif/info.json

(https://dezoomify.ophir.dev/zoommanager.js:221)
```

If I select "Generic dezoomer", it will say:

```
Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://media.britishmuseum.org/iiif/Repository/Documents/2018_2/21_14/8a50c80c_405a_4136_ab8b_a88e00ea42e3/PPA24814.ptif/info.json
```

But that URL loads in my web browser (Firefox):

```
{
  "@context" : "http://iiif.io/api/image/2/context.json",
  "@id" : "https://media.britishmuseum.org/iiif/Repository/Documents/2018_2/21_14/8a50c80c_405a_4136_ab8b_a88e00ea42e3/PPA24814.ptif",
  "protocol" : "http://iiif.io/api/image",
  "width" : 6619,
  "height" : 3860,
  "sizes" : [
     { "width" : 103, "height" : 60 },
     { "width" : 206, "height" : 120 },
     { "width" : 413, "height" : 241 },
     { "width" : 827, "height" : 482 }
  ],
  "tiles" : [
     { "width" : 128, "height" : 128, "scaleFactors" : [ 1, 2, 4, 8, 16, 32, 64 ] }
  ],
  "profile" : [
     "http://iiif.io/api/image/2/level1.json",
     { "formats" : [ "jpg" ],
       "qualities" : [ "native","color","gray" ],
       "supports" : ["regionByPct","sizeByForcedWh","sizeByWh","sizeAboveFull","rotationBy90s","mirroring","gray"] }
  ]
}
```
It's the same with the image in issue #507.

**Comment by lovasoa** [comment] 2023-12-29 16:41
I think this issue is a duplicate of https://github.com/lovasoa/dezoomify/issues/764

**Closed as completed by lovasoa** 2023-12-29 16:41 UTC
Labels: duplicate
