### ISSUE TITLE
Problem with artsy's pictures

### ISSUE THREAD

**Issue by Heliodore70** [lovasoa/dezoomify#177] opened 2017-10-02 14:32 UTC
I can't dezoomify artsy's pictures any more too.

**Comment by EdoLom** [comment] 2017-10-05 21:47
I confirm that dezoomify does not work (anymore) with Artsy: «Error: Invalid JSON: [URL here] (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)»
Using the developer tools does not allow to get the json file, as it is likely obtained through POST rather than the GET method.

**Comment by lovasoa** [comment] 2020-08-30 21:51
Duplicate of #129

**Closed by lovasoa** 2020-08-30 21:51 UTC
