### ISSUE TITLE
Limited zoom

### ISSUE THREAD

**Issue by nrkus** [lovasoa/dezoomify#409] opened 2020-06-22 16:54 UTC
I've been trying this on Google Arts and Culture, and for larger images the result isn't zoomed all the way. Take for instance :

https://artsandculture.google.com/asset/the-birth-of-venus-sandro-botticelli/MQEeq50LABEBVg

It generates an image that is 13 667 pixel wide which is already great, but still significantly lower resolution than the original. I'm wondering if it would be possible to recreate the image in its full resolution, or is there some technical limitation that prevents this?

**Comment by lovasoa** [comment] 2020-06-22 17:00
Duplicate of #296

**Closed by lovasoa** 2020-06-22 17:00 UTC

**Comment by lovasoa** [comment] 2020-06-22 17:01
Hello, 
  This has already been reported before. See the discussion in the previous issue for more details. You can also comment there. The quick solution is to just use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/)

**Comment by nrkus** [comment] 2020-06-22 17:11
Yes I just saw that and was about to delete this, thanks and apologies.
