### ISSUE TITLE
[new site support] rgada.info

### ISSUE THREAD

**Issue by Brighter2** [lovasoa/dezoomify#516] opened 2021-01-23 08:11 UTC
### Site name and desciption
rgada.info is the site of Russian State Archive of Ancient Acts. Huge amount of documents stored there is now kept in zoomify format.

Typically a document is organized like that: http://rgada.info/poisk/index2.php?str=210-ukaz_2&opisanie=%D0%A0%D0%B0%D0%B7%D1%80%D1%8F%D0%B4%D0%BD%D1%8B%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BA%D0%B0%D0%B7,%20%D0%B3.%20%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0..%20%D0%A3%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C#

Using a link like that with dezoomify returns "Unable to find a proper dezoomer" error. Both dezoomify-rs and dezoomify-extension can't find valid URL, nor XML link can't be found in the Firefox network inspector.

Actually, for almost every document there is direct access to its ZIF files, e.g. http://rgada.info/opisi/210-ukaz_2/ They are downloadable, but that doesn't help too, because I can't find the way to open them locally.

**Comment by lovasoa** [comment] 2021-01-23 09:30
ZIF files are just tiff files. You can rename them from .zif to .tiff and open them with The Gimp for instance.

**Comment by Brighter2** [comment] 2021-01-25 17:48
> ZIF files are just tiff files. You can rename them from .zif to .tiff and open them with The Gimp for instance.

That would be too easy task then. I've tried renaming ZIFs to TIFF but that didn't help. None of my viewers/editors could open those TIFFs :(

**Comment by lovasoa** [comment] 2021-01-26 09:20
Did you try the gimp ? https://gimp.org/

**Comment by Brighter2** [comment] 2021-01-31 09:26
That's what GIMP's latest version says when trying to open .zif to .tiff renamed file:

Not a TIFF file, bad version number 8235 (0x202b)

**Comment by lovasoa** [comment] 2021-01-31 15:10
I'm closing this as a duplicate of https://github.com/lovasoa/dezoomify/issues/486

**Closed by lovasoa** 2021-01-31 15:10 UTC
Labels: new site support

**Comment by lovasoa** [comment] 2021-01-31 15:22
I just tried, and I can confirm that Gimp can open the image.

![image](https://user-images.githubusercontent.com/552629/106388603-94c92880-63df-11eb-970a-6b48f6cf0680.png)

![image](https://user-images.githubusercontent.com/552629/106388642-d4901000-63df-11eb-9681-0e521de67b7d.png)

![image](https://user-images.githubusercontent.com/552629/106388731-2c2e7b80-63e0-11eb-9dcb-f8597bb1f643.png)

![image](https://user-images.githubusercontent.com/552629/106388755-3f414b80-63e0-11eb-8551-b23b5b7bb3e4.png)
 
just ignore the messages

![image](https://user-images.githubusercontent.com/552629/106388800-7283da80-63e0-11eb-91c9-b9bdd703c255.png)
