### ISSUE TITLE
Can't download any image from vangoghmuseum.nl

### ISSUE THREAD

**Issue by robbitara** [lovasoa/dezoomify#487] opened 2020-11-12 13:32 UTC
I was trying to download [this image](https://www.vangoghmuseum.nl/en/collection/s0083V1962), but I got an error during the download process.
I get the same error message with any image on that site.

### Current error message

```
Uncaught Error: Invalid JSON:
https://micrio.vangoghmuseum.nl/iiif/WAbpi/info.json

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:208)
```

**Comment by lovasoa** [comment] 2020-11-12 16:13
They are using [micrio](https://micr.io) with what seems to be a non-standard URL structure for IIIF images.
This means you cannot use the standard IIIF dezoomer that is triggered for the info.json.

However, you can still download this image using the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial). In this case, you would give it the following URL template : 

```
https://micrio-cdn.vangoghmuseum.nl/WAbpi/0/{{X}}-{{Y}}.jpg
```

**Comment by lovasoa** [comment] 2020-11-12 16:16
Duplicate of #309

**Closed by lovasoa** 2020-11-12 16:16 UTC
Labels: new site support

**Comment by dancorpse** [comment] 2021-01-25 02:20
Thanks for the explanation. Mark.

**Comment by janedoevie** [comment] 2025-05-02 19:47
I was not able to use this workaround. I am getting an error as well.
