### ISSUE TITLE
g2.ltfc.net

### ISSUE THREAD

**Issue by 954097023** [lovasoa/dezoomify#593] opened 2021-12-18 16:48 UTC
Hello everyone,

 I am having issues when trying to download http://g2.ltfc.net/view/SHIY/5fb14b03c837f3173590a185

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
http://g2.ltfc.net/view/SHIY/5fb14b03c837f3173590a185

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2021-12-21 09:27
Duplicate of https://github.com/lovasoa/dezoomify/issues/572

**Closed by lovasoa** 2021-12-21 09:27 UTC
Labels: new site support
