### ISSUE TITLE
Artsy images does not work in dezoomify

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#166] opened 2017-08-03 07:05 UTC
For example: https://www.artsy.net/artwork/henri-matisse-femme-au-chapeau-woman-with-a-hat

There's a choice in dezoomify for artsy, but it's not work. Thank you!

**Comment by kioja** [comment] 2017-09-06 17:24
Any idea about what happened?

**Comment by EdoLom** [comment] 2017-10-05 21:47
I confirm that dezoomify does not work (anymore) with Artsy: «Error: Invalid JSON: [URL here] (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)»
Using the developer tools does not allow to get the json file, as it is likely obtained through POST rather than the GET method.

**Comment by lovasoa** [comment] 2020-08-30 21:51
Duplicate of #129

**Closed by lovasoa** 2020-08-30 21:51 UTC
