### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Colliwomple** [lovasoa/dezoomify#565] opened 2021-06-30 19:12 UTC
On the dezoomify website i get when i try to paste a link from arts and culture

https://artsandculture.google.com/asset/peachtime-atom-n-carolina-state-college-class-on-industrial-atom-developments/iQEaJFYdCPCOWQ
 
"Error: Unable to find arts and culture image metadata URL

(https://dezoomify.ophir.dev/dezoomify/dezoomers/arts-culture.js:7)"

The same with the firefox extension. Can someone help me to fix this issue ? Same under Firefox and Safari 
Thank you in advance !

**Comment by lovasoa** [comment] 2021-06-30 21:45
Duplicate of https://github.com/lovasoa/dezoomify/issues/556

**Closed by lovasoa** 2021-06-30 21:45 UTC
Labels: bug
