### ISSUE TITLE
[new site support] www.easyzoom.com

### ISSUE THREAD

**Issue by Ethan-Sharp** [lovasoa/dezoomify#534] opened 2021-03-07 21:45 UTC
### Site name and desciption
EasyZoom
[https://www.easyzoom.com/](url)

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

### Example URLs
[https://www.easyzoom.com/image/94415](url)
[https://www.easyzoom.com/image/92594](url)

Image tile URLs that I found are very long, beginnings look like this

`data:image/jpeg;base64,/9j/`...

ends look like this

...`//ZUA==`

[https://justpaste.it/9qlq7](url)

### Current error message

```
Uncaught Error: Unable to find a proper dezoomer for:
https://www.easyzoom.com/image/94415

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```

**Comment by lovasoa** [comment] 2021-03-08 10:29
Duplicate of https://github.com/lovasoa/dezoomify/issues/287 and https://github.com/lovasoa/dezoomify/issues/439

**Closed by lovasoa** 2021-03-08 10:29 UTC
Labels: new site support

**Comment by lovasoa** [comment] 2021-03-08 10:35
https://www.google.com/search?q=dezoomify+easyzoom
