### ISSUE TITLE
sammlung.belvedere.at

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#444] opened 2020-08-18 12:19 UTC
Hello everyone,

 I am having issues when trying to download https://sammlung.belvedere.at/internal/media/zoomdispatcher/5728/info.json
 The image on https://sammlung.belvedere.at/objects/3700/almosenspende-des-hl-oswald?
Dezoomify reports:

```
Error: Unable to fetch https://sammlung.belvedere.at/internal/media/zoomdispatcher/5728/info.json

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:418)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2020-08-18 13:00
Duplicate of https://github.com/lovasoa/dezoomify/issues/440

**Closed by lovasoa** 2020-08-18 13:00 UTC

**Comment by lovasoa** [comment] 2020-08-18 13:03
@gp270661 : I already asked you to please avoid opening multiple threads for a single issue. It is starting to be very annoying. Please don't do it again, or I'll have to block you.

**Comment by lovasoa** [comment] 2020-08-18 13:06
If you want to add more information or comments on a previous issue, you can do so in the issue itself, even if it's closed. If the details you add make the previously closed issue actionable, we can reopen it. Do not open new issues for the same image.

**Comment by lovasoa** [comment] 2020-08-18 13:10
Additionally, for the page you give on sammlung.belvedere.at, you can download the source image in full quality from the web viewer itself. You don't need dezoomify.
