### ISSUE TITLE
Google Arts&Culture Not Grabbing Max Resolution

### ISSUE THREAD

**Issue by cygnusthesw44n** [lovasoa/dezoomify#357] opened 2020-02-27 04:04 UTC
Hello,

I had just started using dezoomify recently after months long of a hiatus. I use it for google arts and culture. 

Lately, Almost every single image I grab comes off in low-resolution. This is evident on the size of the files, most range from 1-2mb and even kb at times. In contrast to this, on the google arts&culture site I could zoom in much further and see more detail on the same image.

One example is the image in the link below.
(set to googlearts&&culture in dezoomify)
https://g.co/arts/5MRXW34E1dMzabuE8

the size turns out to be just a measly 1mb with a resolution of 1926*1156. In the past every image I've dezoomify had always resulted in a larger file and resolution. 

Help on a solution would be wonderfully appreciated!.

**Comment by lovasoa** [comment] 2020-02-27 09:46
Hello, I'm closing this as a duplicate of #296, but I'm still open to discussion about this topic. The limit is artificial and could be set higher. You can comment with your opinion on  #296.

**Comment by lovasoa** [comment] 2020-02-27 10:21
Oh, actually, let me reopen this issue. It is not a duplicate. `UI.MAX_CANVAS_AREA` is `268435456` and the available zoom levels are (according to dezoomify-rs, which downloads the largest image without problems):

```
0. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele (  482 x   289 pixels,     1 tiles)
1. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele (  963 x   578 pixels,     4 tiles)
2. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele ( 1926 x  1156 pixels,    12 tiles)
3. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele ( 3851 x  2311 pixels,    40 tiles)
4. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele ( 7701 x  4621 pixels,   160 tiles)
5. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele (15401 x  9241 pixels,   589 tiles)
6. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele (30802 x 18482 pixels,  2257 tiles)
7. Australian troops disembarking at Alexandria after the evacuation of Greece - Ivor Hele (61604 x 36963 pixels,  8833 tiles)
```

The largest zoom level that fits into dezoomify's constraints is level 5, but it downloads only level 2.

It is because dezoomify resolves the list of zoom levels to 
https://lh3.ggpht.com/lZhK5P8xQfJc429-Dm4T4Yn1xzMS6fyBjMhpokVBKeoovKCRtCZ875YvTQrY=g

Whereas dezoomify-rs finds 
https://lh3.ggpht.com/txSQzJ7Jye8GCQtiMiPiapk4v-jo4cr6BwtSRLEgYCGKgZBMTtk40-gutXI=g

So it seems to be a problem with dezoomify, and it needs more investigation...

**Comment by lovasoa** [comment] 2020-02-27 10:44
In the meantime, I uploaded the max resolution to wikimedia https://commons.wikimedia.org/wiki/File:Australian_troops_disembarking_at_Alexandria_after_the_evacuation_of_Greece_-_Ivor_Hele.jpg

**Comment by cygnusthesw44n** [comment] 2020-02-27 16:52
Thank-you that's great to hear. I appreciate you uploading The max
resolution file to wikimedia but it wasn't necessary. You may delete it if
you wish. I managed to grab the image using dezoomify-rs.

Thank-you once more.

**Comment by lovasoa** [comment] 2020-02-27 18:01
> You may delete it if you wish.

Of course I'm not deleting it ! It's already in use on 4 wikipedia pages in two languages and on wikidata !

**Comment by lovasoa** [comment] 2020-02-27 18:04
I encourage you to upload the images that you download and that are free of copyright to wikimedia too 😃

**Closed** 2020-02-27 22:34 UTC
Labels: bug

**Comment by lovasoa** [comment] 2020-02-27 22:36
Ok, the bug should be fixed now. The limits mentioned in #296 still apply, but dezoomify shouldn't miss higher zoomlevels as it did.
