### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Akossimon** [lovasoa/dezoomify#795] opened 2024-05-28 13:49 UTC
following link does not allow for your plug to be used:

https://fineartamerica.com/featured/count-leopold-joseph-von-daun-1705-66-fieldmarshall-and-austrian-commander-in-chief-austrian-school.html

**Comment by lovasoa** [comment] 2024-05-28 18:19
I'm closing this as a duplicate of https://github.com/lovasoa/dezoomify/issues/707

**Closed as completed** 2024-05-28 18:20 UTC
Labels: new site support
