### ISSUE TITLE
[bug] - Uncaught Error: Unable to find arts and culture image metadata URL

### ISSUE THREAD

**Issue by jeffp1717** [lovasoa/dezoomify#633] opened 2022-07-11 13:50 UTC
Google Arts and Culture links are not currently downloading in dezoomify or dezoomify-rs.

**Describe the bug**
Uncaught Error: Unable to find arts and culture image metadata URL

(https://dezoomify.ophir.dev/dezoomers/arts-culture.js:7)

**To Reproduce**
Trying this URL, but looks like all Google Arts and Culture links are broken currently: https://artsandculture.google.com/asset/im-sommer-in-summer/XwGV-gpFGOZavQ

**Browser:**
 - Chrome
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Comment by lovasoa** [comment] 2022-07-22 12:43
Google had changed the format of their pages.
It's fixed in dezoomify now.

Duplicate of https://github.com/lovasoa/dezoomify/issues/638

**Closed by lovasoa** 2022-07-22 12:43 UTC
Labels: bug
