### ISSUE TITLE
[bug] Google Chrome (not responding) high ram usage

### ISSUE THREAD

**Issue by AnotherCollector** [lovasoa/dezoomify#473] opened 2020-09-30 09:02 UTC
After using dezoomify chrome extension for a while I ran into this issue where basically whenever I start chrome it takes few seconds then it becomes unresponsive for about 30 seconds or so while using about 4gb of ram (high resource usage) I tried generating dump file but it was so big (4gb) ! I tried disabling, uninstalling the extension with no success so I thought maybe the problem is with Chrome so I went and reinstalled it and everything went fine and worked smoothly, However, once I installed the extension once again and used it for sometime the issue returned once again.
I work mostly with maps so images I download are kinda big (150mb sometimes)

**Browser:**
- Google Chrome
- Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by lovasoa** [comment] 2020-09-30 16:59
I think this is a duplicate of https://github.com/lovasoa/dezoomify-extension/issues/13

**Comment by lovasoa** [comment] 2020-09-30 17:00
If you can consistently reproduce the bug, please post reproduction instructions on the linked issue, it should help with debugging.

**Closed** 2020-09-30 17:00 UTC
Labels: bug
