### ISSUE TITLE
Barnes Collection

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#463] opened 2020-09-18 03:50 UTC
### Site name and desciption
https://collection.barnesfoundation.org/objects/6365/Red-Madras-Headdress-(Le-Madras-rouge)/

I have downloaded both the browser extension and dezoomify-rs and have had good success with both of them. I saw your earlier post regarding the incorrect json files on this page, and how they need to be edited, but I don't know how to do this. 

Can you give me some info on how to download the json? Once it's downloaded, what can I use to edit it, and then how would I load it to -rs?

Thanks for your help...

**Comment by lovasoa** [comment] 2020-09-18 08:00
I am closing this as a duplicate of #417. But I will write a more detailed explanation there.

**Closed by lovasoa** 2020-09-18 08:00 UTC
Labels: new site support
