### ISSUE TITLE
[new site support] bibliotheques-specialisees.paris.fr

### ISSUE THREAD

**Issue by TsiVit** [lovasoa/dezoomify#595] opened 2021-12-22 21:45 UTC
https://bibliotheques-specialisees.paris.fr/
https://gallica.bnf.fr/

the -rs version that is not working with this two. Gallica itself is not the problem as picture can be dw through request based on url (that was already mentioned before), but gallica has many external references including to bibliotheques-specialisees.

### Example URLs
https://bibliotheques-specialisees.paris.fr/ark:/73873/pf0001762675?posInSet=10&queryId=32f4d049-faa0-473d-8faf-d42f4fbc83b1
https://bibliotheques-specialisees.paris.fr/ark:/73873/pf0001762675/v0001.simple.highlight=Bernard%20Villemot.selectedTab=record

### Current error message
Unable to create the dezoomer

**Comment by lovasoa** [comment] 2021-12-23 11:30
duplicate of https://github.com/lovasoa/dezoomify/issues/457

**Closed by lovasoa** 2021-12-23 11:30 UTC
Labels: new site support

**Comment by TsiVit** [comment] 2021-12-23 13:31
But I meant -rs version exactly, not just browser app as used in reference.
