### ISSUE TITLE
Cant download Seadragon/artsy.net image?

### ISSUE THREAD

**Issue by cookiealexd123** [lovasoa/dezoomify#214] opened 2018-03-16 21:42 UTC
tried using network>XHR tactic but it didnt produce any results.
when i use the regular url searcher for the dezoom page is says "Uncaught Error: Invalid JSON"
could someone help me with this? id really like the full HD image. alex

https://www.artsy.net/artwork/voka-marilyn-monroe

**Comment by dancorpse** [comment] 2018-03-21 10:16
I always use Generic dezoomer for artsy.net, bcs the regular way does not work.
Try: https://d32dm0rphc51dk.cloudfront.net/CmBzmxnXK5xigzJxfounhg/dztiles/12/{{X}}_{{Y}}.jpg

**Comment by lovasoa** [comment] 2020-08-30 21:52
Duplicate of #129

**Closed by lovasoa** 2020-08-30 21:52 UTC
