### ISSUE TITLE
media.davidrumsey.com

### ISSUE THREAD

**Issue by algae21** [lovasoa/dezoomify#465] opened 2020-09-23 00:21 UTC
Hello everyone,

 I am having issues when trying to download https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/162/8345000.jp2&x=12000&y=13500&width=750&height=11&level=1

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/162/8345000.jp2&x=12000&y=13500&width=750&height=11&level=1

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment] 2020-09-23 05:55
duplicate of #339

**Closed** 2020-09-23 05:55 UTC
