### ISSUE TITLE
Bonhams images

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#508] opened 2021-01-05 06:14 UTC
Hi lovasoa and happy new year!
I am unable to get the biggest zoomed image from Bonhams.
Here is an example page:
https://www.bonhams.com/auctions/26712/lot/20/?category=list&length=12&page=2
When you have time could you help me please!

Thank you
aw

**Comment by lovasoa** [comment] 2021-01-05 09:08
Hello, and happy new year to you !
  I am closing this issue as a duplicate of https://github.com/lovasoa/dezoomify/issues/123
  Please search for existing issues before opening new ones.

**Comment by lovasoa** [comment] 2021-01-05 09:09
![](https://images2.bonhams.com/image?src=Images%2Flive%2F2020-11%2F20%2F25005985-7-2.jpg&tile=1:1)

**Closed by lovasoa** 2021-01-05 09:08 UTC

**Comment by awhizard** [comment] 2021-01-05 13:25
Thank you and sorry for the duplicate! 
aw
